#!/bin/sh

# invoke global X session script
#. /etc/X11/Xsession

if [ -d "/snap/bin" ] ; then
export PATH="$PATH:/snap/bin"
fi

# monitor layout and wallpaper
~/.screenlayout/danpc.sh 
nitrogen --restore

# pywal 
[ -d ~/.cache/wal ] && wal -R && . ~/.cache/wal/colors.sh

# compositor
picom -b 

# Xresources
xrdb -merge -I$HOME ~/.Xresources

# switch super_L and alt_L
xmodmap -e 'remove mod1 = Alt_L'
xmodmap -e 'remove mod4 = Super_L'
xmodmap -e 'add mod1 = Super_L'
xmodmap -e 'add mod4 = Alt_L'

# ssh-agent
eval $(ssh-agent)

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# Simple X Hotkey Daemon
sxhkd &

# launch i3 wrapped in dbus to ensure DBus envi variables set 
# see playerctl github readme 
exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) i3
