#! /bin/sh

killall sxhkd; sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc_bspwm "$HOME"/.config/sxhkd/sxhkdrc &
killall polybar; polybar default &
picom -b

# reparenting fix for java guis
wmname compiz

# pywal colors
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

wal --theme base16-atelier-estuary
wal -R
feh --bg-fill ~/Pictures/wallpaper/lake.png

# bspc
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mouse
bspc config pointer_modifier alt
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating

# clipboard manager
greenclip daemon &

# make CapsLock behave like Ctrl:
# setxkbmap -option ctrl:nocaps

# make short-pressed Ctrl behave like Escape:
# xcape -e 'Control_L=Escape'
